# Generated by Django 4.2.4 on 2023-08-26 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ad',
            new_name='Ads',
        ),
    ]
