# Generated by Django 4.2.4 on 2023-08-26 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_ad_ads'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='lorem',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
