# Generated by Django 4.2.4 on 2023-09-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_information_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='information',
            name='bio',
        ),
    ]
